start header
SkliarovskaAnastasiia/CodeWizards-team-project pull request #4
Opened 2024-10-17 13:46 UTC by Volodymyr-Vo

2024-10-17 15:21 UTC, SkliarovskaAnastasiia requested changes
Писати код в своєму файлі

2024-10-18 18:46 UTC, SkliarovskaAnastasiia commented on src/partials/header.html
> +    <div class="back">
Цей div зайвий

2024-10-18 18:47 UTC, SkliarovskaAnastasiia commented on src/partials/header.html
> +      <div class="header-container">
Клас header-container краще додати як додатковий клас до div з класом container, тоді цей div буде зайвим

2024-10-18 18:50 UTC, SkliarovskaAnastasiia commented on src/partials/header.html
> +            <use href="..//images/icons.svg#icon-burger-btn"></use>
Потрібно прибрати 1 крапку на початку шляху до іконок та 1 / зайвий

2024-10-18 18:54 UTC, SkliarovskaAnastasiia commented on src/css/header.css
> +  border: 0;
Для кнопки краще обнулити line-height

2024-10-18 18:58 UTC, SkliarovskaAnastasiia commented on src/css/header.css
> +  margin: 0 auto;
Ці стилі зайві, фон має бути прозорий, його краще задати на секцію з класом section,
max-width та margin наслідуються з загальних стилів для контейнера,
height краще не задавати, елемент розшириться по висоті за рахунок padding

2024-10-18 19:02 UTC, SkliarovskaAnastasiia commented on src/css/header.css
> +  .header-list {
Тут має бути клас header-container

2024-10-18 19:06 UTC, SkliarovskaAnastasiia commented on src/css/header.css
> +  }
Ці стилі також зайві

2024-10-18 19:09 UTC, SkliarovskaAnastasiia commented on src/css/header.css
> +    text-transform: uppercase;
Для кнопки можна задати transition, щоб зміна фону відбувалася плавно (можна взяти з домашки 250ms cubic-bezier(0.4, 0, 0.2, 1))

2024-10-18 19:13 UTC, SkliarovskaAnastasiia commented on src/partials/header.html
> +              <a href="#vegetables">How It Works</a>How It Works
Тут має бути текст Vegetables, після закриваючого тегу зайвий текст

2024-10-18 19:16 UTC, SkliarovskaAnastasiia requested changes
Залишила коментарі в коді

2024-10-19 08:06 UTC, Volodymyr-Vo commented on src/partials/header.html
> +            <use href="..//images/icons.svg#icon-burger-btn"></use>
+

2024-10-19 08:15 UTC, Volodymyr-Vo commented on src/css/header.css
> +  border: 0;
+

2024-10-19 08:17 UTC, Volodymyr-Vo commented on src/partials/header.html
> +    <div class="back">
Забув прибрати)

2024-10-19 08:18 UTC, Volodymyr-Vo commented on src/partials/header.html
> +      <div class="header-container">
Забув прибрати)

2024-10-19 08:24 UTC, Volodymyr-Vo commented on src/partials/header.html
> +      <div class="header-container">
+

2024-10-19 08:31 UTC, Volodymyr-Vo commented on src/css/header.css
> +  .header-list {
+

2024-10-19 08:34 UTC, Volodymyr-Vo commented on src/css/header.css
> +  }
+

2024-10-19 08:39 UTC, Volodymyr-Vo commented on src/css/header.css
> +    text-transform: uppercase;
+

2024-10-19 08:41 UTC, Volodymyr-Vo commented on src/partials/header.html
> +              <a href="#vegetables">How It Works</a>How It Works
+

2024-10-19 10:28 UTC, Volodymyr-Vo commented on src/css/header.css
> +  margin: 0 auto;
+

2024-10-19 11:32 UTC, SkliarovskaAnastasiia commented on src/css/header.css
> +  padding: 20px;
Прибрати width з header-container

2024-10-19 11:39 UTC, Volodymyr-Vo commented on src/css/header.css
> +  padding: 20px;
+

2024-10-19 11:41 UTC, SkliarovskaAnastasiia approved these changes

2024-10-19 11:42 UTC, merged