Section advertisement
SkliarovskaAnastasiia/CodeWizards-team-project pull request #5
Opened 2024-10-17 17:24 UTC by LarysaDrahuzia

Я все виконала, перевір будь ласка

2024-10-18 05:15 UTC, SkliarovskaAnastasiia requested changes
1. Для секції потрібно додати додатковий клас, який знаходиться у файлі base.css та видалити падінги в своєму файлі.
2. Контейнеру не потрібно задавати властивості flex та перевизначати ширину, тільки  padding-left та padding-right.
3. Тексту не потрібно задавати фон, тільки всій секції та частині з зеленим фоном.
4.Елементам не потрібно визначати висоту.
5.Щоб текст не прилипав до рамки можна текст поділити на 2 р(1-з білим текстом та фоном, 2-з чорним текстом) і кожній задати padding-left

2024-10-19 12:21 UTC, SkliarovskaAnastasiia commented on src/partials/advertisement.html
> +<section class="slogan-section">
Додати до секції додатковий клас section-paddings та прибрати падінги в css

2024-10-19 12:21 UTC, SkliarovskaAnastasiia commented on src/css/advertisement.css
> +}
Тут прибрати падінги

2024-10-19 12:22 UTC, SkliarovskaAnastasiia commented on src/css/advertisement.css
> +}
Ці властивості тут не потрібні, потрібно їх видалити

2024-10-19 12:38 UTC, SkliarovskaAnastasiia commented on src/css/advertisement.css
> +    line-height: 1.35;
Краще замість height використати padding-top та padding-bottom для мобільних стилів по 3рх, для планшетних - 8рх, на десктопі 0

2024-10-19 12:42 UTC, SkliarovskaAnastasiia commented on src/css/advertisement.css
> +  }
Тут також прибрати падінги

2024-10-19 12:43 UTC, SkliarovskaAnastasiia reviewed
Лишила коментарі в коді

2024-10-19 13:03 UTC, PavloGurskyi commented on src/css/advertisement.css
> +}
прибрав

2024-10-19 13:04 UTC, PavloGurskyi commented on src/css/advertisement.css
> +}
видалив

2024-10-19 13:05 UTC, PavloGurskyi commented on src/css/advertisement.css
> +  }
прибрав

2024-10-19 13:19 UTC, PavloGurskyi commented on src/css/advertisement.css
> +    line-height: 1.35;
видалив цей рядок. він не потрібен

2024-10-19 13:20 UTC, PavloGurskyi commented on src/partials/advertisement.html
> +<section class="slogan-section">
додав

2024-10-19 13:53 UTC, SkliarovskaAnastasiia approved these changes

2024-10-19 13:53 UTC, merged