Menu mobile
SkliarovskaAnastasiia/CodeWizards-team-project pull request #6
Opened 2024-10-17 20:49 UTC by PavloGurskyi

2024-10-18 04:06 UTC, eXocriador reviewed
Залишив коментарі в коді
Трішки підлатати до майбутньої адаптації під планшет, і треба буде ще додати окремий @media в .css, бо загальні стилі по типу контейнерів/секцій там не прокатять
А так в цілому порядок, якщо чисто мобільну через дев тулзи чекати то чітко по макету

2024-10-18 04:06 UTC, eXocriador commented on src/css/mobile-menu.css
> +  width: 155px;
розміри кнопки краще не фіксувати, на випадок зміни змісту, а грати через паддінги, їх достатньо буде

2024-10-18 04:06 UTC, eXocriador commented on src/partials/mobile-menu.html
> +  <div class="container mobile-menu-container">
.container не буде актуальним для менюшки, там на планшетній версії потрібно буде фіксувати меню справа вікном, не фуллскрін
його якщо накидувати - то краще на div.mobile-menu, який буде слугувати враппером на планшетній, бо на самій менюшці відступи неактуальні, а центровка через флекс і так іде

2024-10-18 04:06 UTC, eXocriador commented on src/css/mobile-menu.css
> +  z-index: 999;
background-color краще бахнути на .mobile-menu-container , бо з .mobile-menu потім можна зробити враппер для оверлея
на планшетній буде затінення фону, там буде свій бек з прозорістю

2024-10-18 06:26 UTC, SkliarovskaAnastasiia commented on src/css/mobile-menu.css
> +  border: 0;
Для бордера має бути значення none

2024-10-18 06:33 UTC, SkliarovskaAnastasiia commented on src/css/mobile-menu.css
> +  height: 42px;
Краще висоту та  ширину не фіксувати, а додати падінги

2024-10-18 06:46 UTC, SkliarovskaAnastasiia requested changes
Буде добре також додати transition для елементів, які при ховері змінюються (можна взяти з нашої домашки 250ms cubic-bezier(0.4, 0, 0.2, 1))

2024-10-18 07:23 UTC, eXocriador commented on src/css/mobile-menu.css
> +  height: 42px;
> Краще висоту та  ширину не фіксувати, а додати падінги

Тут фіксація має сенс, тому що кнопки по макету однакові за розміром, тулити падінг на кожну окремо міряючи пікселі від тексту було б дивно. Їх або окремо фіксувати, як і зроблено зараз, або фіксувати тільки по ширині через 100%, які будут упиратися в фікс ширину флекса ul з вертикальними падінгами на самих кнопках.

2024-10-18 09:57 UTC, SkliarovskaAnastasiia commented on src/css/mobile-menu.css
> +  height: 42px;
Перепрошую, не помітила що падінги відрізняються)
Тода краще використати min-width

2024-10-19 14:21 UTC, PavloGurskyi commented on src/css/mobile-menu.css
> +  z-index: 999;
+

2024-10-19 14:37 UTC, PavloGurskyi commented on src/css/mobile-menu.css
> +  border: 0;
скинув

2024-10-19 14:42 UTC, PavloGurskyi commented on src/css/mobile-menu.css
> +  height: 42px;
leave as is

2024-10-19 14:44 UTC, PavloGurskyi commented on src/css/mobile-menu.css
> +  width: 155px;
прибрав

2024-10-19 14:56 UTC, PavloGurskyi commented on src/partials/mobile-menu.html
> +  <div class="container mobile-menu-container">
ok

2024-10-20 06:26 UTC, SkliarovskaAnastasiia commented on src/partials/mobile-menu.html
> +      <button type="button" class="menu-shop-btn">shop now</button>
Кнопку краще зробити якірним посиланням яке скролить до секції your order

2024-10-20 06:32 UTC, SkliarovskaAnastasiia commented on src/css/mobile-menu.css
> +}
Для десктопу меню потрібно приховати

2024-10-20 06:36 UTC, SkliarovskaAnastasiia commented on src/css/mobile-menu.css
> +}
Додати transition

2024-10-20 06:37 UTC, SkliarovskaAnastasiia reviewed
Залишила коментарі в коді

2024-10-20 06:57 UTC, PavloGurskyi commented on src/css/mobile-menu.css
> +}
Я не ховав, бо на десктопі немає кнопки, яким воно викликається )))

2024-10-20 06:59 UTC, PavloGurskyi commented on src/css/mobile-menu.css
> +}
done

2024-10-20 07:02 UTC, PavloGurskyi commented on src/partials/mobile-menu.html
> +      <button type="button" class="menu-shop-btn">shop now</button>
yes

2024-10-20 07:06 UTC, PavloGurskyi commented on src/css/mobile-menu.css
> +}
is done

2024-10-20 07:18 UTC, SkliarovskaAnastasiia commented on src/css/mobile-menu.css
> +}
Але увесь код для меню завантажується

2024-10-20 07:51 UTC, SkliarovskaAnastasiia approved these changes

2024-10-20 07:52 UTC, merged