add hero.html, hero.css
SkliarovskaAnastasiia/CodeWizards-team-project pull request #8
Opened 2024-10-18 03:30 UTC by eXocriador

Все по макету, окрім вигляду <P> на десктоп версії.
Стилі перевизначав, що властивості що розміри елемента - по макету, тупо загадка Жака Фреско якась.
Беки 2х додам пізніше, фікс <p> теж.

![image](https://github.com/user-attachments/assets/95f90567-e1ef-4631-bb1b-a19a4dbef747)

2024-10-18 05:39 UTC, SkliarovskaAnastasiia commented on src/css/hero.css
> +    font-family: Inter Tight;
Текст має наслідувати шрифт з body

2024-10-18 05:53 UTC, SkliarovskaAnastasiia commented on src/css/hero.css
> +  background-repeat: no-repeat;
background-size: cover щоб фон розтягувався на всю сторінку девайсів різної ширини

2024-10-18 06:08 UTC, SkliarovskaAnastasiia requested changes
Щодо тексту спробуй обмежити його по ширині та задати меньший  падінг

2024-10-18 13:43 UTC, PavloGurskyi commented on src/partials/hero.html
> +    <div class="container hero-main-part">
Знайшов помилку:

Якщо ширина екрана 1280px, то все виглядає круто, як на вкладенні #1
![image](https://github.com/user-attachments/assets/60671625-601c-4adf-84e9-55aa6d2afce7)

Але якщо збільшити ширину екрана, то hero-image-part прилипає до лівої сторони. Ось #2:
![image](https://github.com/user-attachments/assets/05c602ee-a964-4d14-b8ae-ae84a42c0f77)

Як це вирішити. Пропоную трохи змінити розмітку. Створюєш div.hero-main-part. Огортаєш ним h1 i p.
Тепер у тебе на одному рівні hero-main-part та hero-image-part. Ці два огортаєш новим дівом hero-wrapper.
Виходить отак:
div.container>div.hero-wrapper>div.hero-main-part+div.hero-image-part.

По css даєш 
.hero-wrapper {
  display: flex;
}
@media (max-width: 1279px) {
  .hero-wrapper {
    flex-direction: column;
  }
}
@media (min-width: 1280px) {
  .hero-wrapper {
    flex-direction: row;
  }
  
  Також там у тбе падінги попливуть, то
  .container {
    padding: 0;
  }

![image](https://github.com/user-attachments/assets/9a1031f3-1bdb-4d46-b3e7-748519fca7fe)

В кінці має вийти отак:
![image](https://github.com/user-attachments/assets/adae8edc-5e03-4222-885e-e9eea08f9b9a)

2024-10-18 13:58 UTC, PavloGurskyi commented on src/css/hero.css
> +  .hero-text {
постав letter-spacing: 0.02em;

2024-10-20 09:03 UTC, SkliarovskaAnastasiia commented on src/css/hero.css
> +}
Щоб не дублювати код, елементу додати додатковий клас з загальних стилів

2024-10-21 06:08 UTC, SkliarovskaAnastasiia commented on src/css/hero.css
> +  position: relative;
relative не потрібен

2024-10-21 06:12 UTC, SkliarovskaAnastasiia reviewed
Щоб не дублювати код, елементу з описом краще додати додатковий клас з загальних стилів section-description, за потреби перевизначити властивості які відрізняються

2024-10-21 08:36 UTC, eXocriador commented on src/css/hero.css
> +  position: relative;
Це для хедера, щоб було на що кріпитися

2024-10-21 08:56 UTC, SkliarovskaAnastasiia commented on src/css/hero.css
> +  position: relative;
хедер буде позіціонуватися відносно body

2024-10-21 08:57 UTC, eXocriador commented on src/css/hero.css
> +  position: relative;
ну ок, прибраав

2024-10-21 09:29 UTC, SkliarovskaAnastasiia approved these changes

2024-10-21 09:29 UTC, merged